name: Compliance Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Linter
        run: sudo apt-get install -y cppcheck

      - name: Run Linter
        run: cppcheck --enable=all --inconclusive --quiet .
